### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by seanmalek2019** [oktadev/okta-graphql-react-express-example#18]
unable to login.  I cloned the project added the okta token url and . clientid and when started the . node at sigin I get redireceted to 400 page see attachment
![Screen Shot 2021-06-01 at 2 21 37 PM](https://user-images.githubusercontent.com/51341131/120372259-ee395980-c2e4-11eb-9aad-d0180cd631f3.png)
![Screen Shot 2021-06-01 at 2 24 36 PM](https://user-images.githubusercontent.com/51341131/120372308-0610dd80-c2e5-11eb-8c52-f89a10fba0fa.png)

**Comment by mraible** [comment]
What redirects do you have configured in your Okta OIDC app? It looks like this expects you to have one that's http://localhost:3000/implicit/callback.

**Comment by seanmalek2019** [comment]
that is what I have.  we checked the those with Lijia Liu (OKTA support) and it looked ok

**Comment by mraible** [comment]
Do you have implicit flow enabled for your app?

**Comment by seanmalek2019** [comment]
yes

**Comment by seanmalek2019** [comment]
![Screen Shot 2021-06-02 at 10 53 35 AM](https://user-images.githubusercontent.com/51341131/120502778-b5ef5500-c390-11eb-94d8-8e61a4d65515.png)

**Comment by mraible** [comment]
Can you try enabling Authorization code too and see if that helps? In the last couple years, we deprecated implicit flow and all our recent JS SDKs expect auth code flow.

**Comment by seanmalek2019** [comment]
I have done that as well but no luck

From: Matt Raible ***@***.***>
Reply-To: oktadev/okta-graphql-react-express-example ***@***.***>
Date: Wednesday, June 2, 2021 at 11:37 AM
To: oktadev/okta-graphql-react-express-example ***@***.***>
Cc: "Malek, Sean" ***@***.***>, Author ***@***.***>
Subject: Re: [oktadev/okta-graphql-react-express-example] unable to login (#18)


Can you try enabling Authorization code too and see if that helps? In the last couple years, we deprecated implicit flow and all our recent JS SDKs expect auth code flow.

**Comment by seanmalek2019** [comment]
OK when I had both turn on then it worked. Thanks

**Comment by mraible** [comment]
I was able to make it work with just implicit flow. 

<img width="698" alt="Screen Shot 2021-06-02 at 10 30 08 AM" src="https://user-images.githubusercontent.com/17892/120517349-999de900-c38d-11eb-833d-6ab018c4f02f.png">

<img width="986" alt="Screen Shot 2021-06-02 at 10 28 52 AM" src="https://user-images.githubusercontent.com/17892/120517384-a28eba80-c38d-11eb-81c3-c39dbf7d148a.png">

Note that this is an old tutorial and implicit flow is no longer recommended. See https://www.youtube.com/watch?v=CHzERullHe8 for more information.
